<?php
/**
 * SeoBox — robots.txt
 * Path: core/seobox/robots-txt.php
 *
 * تنها منبع قوانین robots.txt سایت.
 *
 * چرا کل خروجی از اینجا ساخته می‌شود (نه چند خط اضافه به خروجی وردپرس):
 *
 *   ۱. در استاندارد robots.txt (RFC 9309) هر ربات فقط «خاص‌ترین» گروهی را
 *      که به نامش نوشته شده می‌خواند و گروه «User-agent: *» را کامل نادیده
 *      می‌گیرد. گروه جداگانه برای Googlebot یا GPTBot که فقط چند خط Allow
 *      داشته باشد، یعنی همه ممنوعیت‌های عمومی (سبد خرید، پیشخوان، فیلترها،
 *      جستجو) برای آن ربات برداشته شده است. پس هر گروه اختصاصی باید
 *      قوانین پایه را هم تکرار کند؛ این فایل همین کار را خودکار انجام می‌دهد.
 *   ۲. Googlebot و Bingbot گروه اختصاصی ندارند و همان قوانین عمومی را
 *      می‌خوانند. Google-Extended یک «توکن کنترل» است، نه خزنده؛ فقط تعیین
 *      می‌کند محتوا برای آموزش Gemini استفاده شود یا نه.
 *   ۳. فقط XML سایت‌مپ در دستور Sitemap می‌آید. llms.txt و سایت‌مپ‌های
 *      Markdown (که noindex هستند) در Search Console خطا تولید می‌کردند.
 *   ۴. /wp-includes/ مسدود نمی‌شود؛ گوگل برای رندر صفحه به CSS/JS آن نیاز دارد.
 *
 * هشدار: اگر فایل فیزیکی robots.txt در ریشه سایت باشد، وب‌سرور همان را
 * مستقیم برمی‌گرداند و این قوانین هرگز اجرا نمی‌شوند. در این حالت یک
 * اعلان در پیشخوان نمایش داده می‌شود.
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_filter( 'robots_txt', 'hodima_robots_txt', 20, 2 );

/**
 * @param string          $output خروجی پیش‌فرض وردپرس.
 * @param string|int|bool $public مقدار گزینه blog_public.
 */
function hodima_robots_txt( $output, $public ): string {

	// «از موتورهای جستجو بخواه سایت را ایندکس نکنند» روشن است: خروجی
	// وردپرس (Disallow: /) دست‌نخورده می‌ماند.
	if ( '0' === (string) $public ) {
		return (string) $output;
	}

	$base        = hodima_robots_base_rules();
	$aeo_block   = hodima_robots_aeo_paths();
	$tool_bots   = hodima_robots_blocked_tool_bots();
	$ai_bots     = hodima_robots_ai_bots();
	$aeo_allow   = array_map( static fn( string $p ): string => 'Allow: ' . $p, hodima_robots_aeo_public_paths() );
	$honeypot    = 'Disallow: /*ai-internal-data.md';
	$md_indexing = (bool) apply_filters( 'hodima_md_indexing_enabled', false );

	$lines   = [];
	$lines[] = '# robots.txt — ' . wp_specialchars_decode( get_bloginfo( 'name' ), ENT_QUOTES );
	$lines[] = '# Generated by the Hodima theme (core/seobox/robots-txt.php)';
	$lines[] = '';

	// ── ۱. همه ربات‌ها (شامل Googlebot و Bingbot) ─────────────────────
	$lines[] = '# 1. All crawlers, including Googlebot and Bingbot';
	$lines   = [ ...$lines, ...hodima_robots_group( [ '*' ], [
		...$base,
		...array_map( static fn( string $p ): string => 'Disallow: ' . $p, $aeo_block ),
	] ) ];

	// ── ۲. ابزارهای سئو (مصرف منابع بدون سود برای سایت) ──────────────
	if ( $tool_bots ) {
		$lines[] = '# 2. SEO tool crawlers';
		$lines   = [ ...$lines, ...hodima_robots_group( $tool_bots, [ 'Disallow: /' ] ) ];
	}

	// ── ۳. ربات‌های هوش مصنوعی مجاز: قوانین پایه + نسخه‌های ماشین‌خوان ──
	if ( $ai_bots['allowed'] ) {
		$lines[] = '# 3. AI crawlers (allowed): base rules + machine-readable endpoints';
		$lines   = [ ...$lines, ...hodima_robots_group( $ai_bots['allowed'], [ ...$base, ...$aeo_allow, $honeypot ] ) ];
	}

	// ── ۴. ربات‌های هوش مصنوعی مسدود (از پنل ربات‌گیر) ──────────────
	if ( $ai_bots['blocked'] ) {
		$lines[] = '# 4. AI crawlers (blocked in the bot shield settings)';
		$lines   = [ ...$lines, ...hodima_robots_group( $ai_bots['blocked'], [ 'Disallow: /' ] ) ];
	}

	// ── ۵. فقط اگر ایندکس فایل‌های .md صراحتا روشن شده باشد ───────────
	if ( $md_indexing ) {
		$lines[] = '# 5. Markdown indexing enabled (hodima_md_indexing_enabled)';
		$lines   = [ ...$lines, ...hodima_robots_group( [ 'bingbot' ], [ ...$base, 'Allow: /*/*.md$', $honeypot ] ) ];
	}

	// ── سایت‌مپ‌ها ──────────────────────────────────────────────────────
	foreach ( hodima_robots_sitemaps( $md_indexing ) as $sitemap ) {
		$lines[] = 'Sitemap: ' . $sitemap;
	}

	return implode( "\n", (array) apply_filters( 'hodima_robots_lines', $lines ) ) . "\n";
}

/** یک گروه: چند User-agent پشت سر هم و بعد قوانین مشترک. */
function hodima_robots_group( array $agents, array $rules ): array {
	return [
		...array_map( static fn( string $agent ): string => 'User-agent: ' . $agent, $agents ),
		...array_values( array_unique( $rules ) ),
		'',
	];
}

/**
 * قوانین پایه برای همه گروه‌هایی که اجازه خزش دارند.
 *
 * پارامترها هم با «?» و هم با «&» بسته می‌شوند؛ الگوی «/*?orderby=» فقط
 * وقتی کار می‌کند که orderby اولین پارامتر آدرس باشد.
 */
function hodima_robots_base_rules(): array {

	$rules = [
		'Disallow: /wp-admin/',
		'Allow: /wp-admin/admin-ajax.php',
		'Disallow: /xmlrpc.php',
		'Disallow: /readme.html',
		'Disallow: /license.txt',
		'Disallow: /search/',
		'Disallow: /author/',
		'Disallow: /*/embed/',
		'Disallow: /feed/',
		'Disallow: /*/feed/',
		'Disallow: /comments/feed/',
	];

	// فید پادکست زیر /feed/ است و باید برای اپ‌های پادکست باز بماند
	if ( '1' === (string) get_option( 'hodima_podcast_status', '1' ) ) {
		$rules[] = 'Allow: /feed/podcast/';
	}

	foreach ( hodima_robots_private_paths() as $path ) {
		$rules[] = 'Disallow: ' . $path;
	}

	$params = (array) apply_filters( 'hodima_robots_blocked_params', [
		's', 'replytocom', 'add-to-cart', 'wc-ajax', 'orderby', 'filter_', 'query_type_',
		'min_price', 'max_price', 'stock_status', 'rating_filter', 'per_page', 'per_row', 'v',
	] );

	foreach ( $params as $param ) {
		// پیشوندهایی مثل filter_ و query_type_ علامت = ندارند
		$suffix  = str_ends_with( $param, '_' ) ? '' : '=';
		$rules[] = 'Disallow: /*?' . $param . $suffix;
		$rules[] = 'Disallow: /*&' . $param . $suffix;
	}

	return $rules;
}

/**
 * صفحات خصوصی فروشگاه و حساب کاربری.
 * مسیر سبد، تسویه‌حساب و حساب کاربری از خود ووکامرس خوانده می‌شود تا با
 * تغییر نامک برگه‌ها، قانون هم درست بماند.
 */
function hodima_robots_private_paths(): array {

	$paths = [ '/cart/', '/checkout/', '/my-account/' ];

	if ( function_exists( 'hodima_wc_active' ) && hodima_wc_active() && function_exists( 'wc_get_page_id' ) ) {
		$paths = [];
		foreach ( [ 'cart', 'checkout', 'myaccount' ] as $page ) {
			$page_id = (int) wc_get_page_id( $page );
			$uri     = $page_id > 0 ? get_page_uri( $page_id ) : '';
			if ( is_string( $uri ) && '' !== $uri ) {
				$paths[] = '/' . trim( $uri, '/' ) . '/';
			}
		}
	}

	$extra = [ '/wishlist/', '/compare/', '/login/', '/register/', '/thank-you/', '/track-your-order/', '/price/' ];

	if ( defined( 'HODIMA_USER_PANEL_ENABLED' ) && HODIMA_USER_PANEL_ENABLED ) {
		$extra[] = '/user-panel/';
	}

	return array_values( array_unique( (array) apply_filters( 'hodima_robots_private_paths', [ ...$paths, ...$extra ] ) ) );
}

/** نسخه‌های ماشین‌خوان که فقط ربات‌های هوش مصنوعی مجاز می‌بینند. */
function hodima_robots_aeo_public_paths(): array {
	return [ '/*/*.md$', '/*/llm-search', '/*/llms.txt', '/*/llms-full.txt', '/*/ai-feed.json', '/*/openapi.json' ];
}

/** مسیرهای ماشین‌خوان و داخلی که برای ربات‌های عادی بسته‌اند. */
function hodima_robots_aeo_paths(): array {
	return [
		'/*.md$',
		...array_slice( hodima_robots_aeo_public_paths(), 1 ),
		'/ai-analytics.json',
		'/*ai-internal-data.md',
		'/wp-json/hodima-tc/',
	];
}

/** خزنده‌های ابزارهای سئو که کل سایت برایشان بسته است. */
function hodima_robots_blocked_tool_bots(): array {
	return array_values( (array) apply_filters( 'hodima_robots_blocked_tool_bots', [
		'SemrushBot', 'AhrefsBot', 'MJ12bot', 'DotBot', 'rogerbot', 'BLEXBot', 'PetalBot',
	] ) );
}

/**
 * ربات‌های هوش مصنوعی، تقسیم‌شده بر اساس تنظیمات پنل ربات‌گیر.
 *
 * @return array{allowed: list<string>, blocked: list<string>}
 */
function hodima_robots_ai_bots(): array {

	$known = class_exists( 'Hodima_Bot_Shield' )
		? array_keys( Hodima_Bot_Shield::BOTS )
		: [ 'GPTBot', 'ChatGPT-User', 'OAI-SearchBot', 'ClaudeBot', 'Claude-User', 'Claude-SearchBot', 'Google-Extended', 'PerplexityBot', 'Perplexity-User' ];

	// نام قدیمی Anthropic؛ برای سازگاری
	$known[] = 'anthropic-ai';

	$settings = (array) get_option( 'hodima_ai_bot_settings', [] );
	$tools    = array_map( 'strtolower', hodima_robots_blocked_tool_bots() );
	$result   = [ 'allowed' => [], 'blocked' => [] ];

	foreach ( array_unique( $known ) as $bot ) {
		if ( in_array( strtolower( $bot ), $tools, true ) ) {
			continue; // در گروه ابزارهای سئو کامل بسته شده
		}
		$result[ '0' === (string) ( $settings[ $bot ] ?? '1' ) ? 'blocked' : 'allowed' ][] = $bot;
	}

	return $result;
}

/** فقط سایت‌مپ‌های XML معتبر. */
function hodima_robots_sitemaps( bool $md_indexing ): array {

	$sitemaps = [];

	if ( '1' === (string) get_option( 'hodima_sitemap_status', '1' ) ) {
		$sitemaps[] = home_url( '/sitemap.xml' );
	} elseif ( function_exists( 'wp_sitemaps_get_server' ) && wp_sitemaps_get_server()->sitemaps_enabled() ) {
		$sitemaps[] = home_url( '/wp-sitemap.xml' );
	}

	// سایت‌مپ Markdown فقط وقتی معنا دارد که فایل‌های .md ایندکس‌پذیر باشند
	if ( $md_indexing ) {
		$sitemaps[] = home_url( '/fa/sitemap-md.xml' );
		$sitemaps[] = home_url( '/en/sitemap-md.xml' );
	}

	return array_values( (array) apply_filters( 'hodima_robots_sitemaps', $sitemaps ) );
}

/* =========================================================================
 * هشدار فایل فیزیکی robots.txt
 * ========================================================================= */

add_action( 'admin_notices', 'hodima_robots_physical_file_notice' );

function hodima_robots_physical_file_notice(): void {

	if ( ! current_user_can( 'manage_options' ) ) {
		return;
	}

	$screen = get_current_screen();
	if ( ! $screen || ! in_array( $screen->id, [ 'dashboard', 'options-reading', 'appearance_page_hodima-settings' ], true ) ) {
		return;
	}

	if ( ! is_file( ABSPATH . 'robots.txt' ) ) {
		return;
	}

	printf(
		'<div class="notice notice-warning"><p><strong>%1$s</strong> %2$s <a href="%3$s" target="_blank" rel="noopener">%4$s</a></p></div>',
		esc_html__( 'robots.txt:', 'hodima' ),
		esc_html__( 'یک فایل فیزیکی robots.txt در ریشه سایت وجود دارد و وب‌سرور همان را نمایش می‌دهد؛ قوانین هوشمند قالب (هماهنگ با سایت‌مپ، ووکامرس و تنظیمات ربات‌گیر) اعمال نمی‌شوند. برای استفاده از قوانین قالب، آن فایل را از هاست حذف کنید.', 'hodima' ),
		esc_url( home_url( '/robots.txt' ) ),
		esc_html__( 'مشاهده robots.txt فعلی', 'hodima' )
	);
}
